### ISSUE TITLE
Undefined Index

### ISSUE THREAD

**Issue by afavata** [mageplaza/magento-2-seo#19]
Magento 2.1.5 - PHP 7.0.15-0ubuntu0.16.04.4

Just reinstalled SEO module with the command:

composer require mageplaza/magento-2-seo-extension:dev-master

Installed succesfully, compiled and cache refreshed.

Now on the frontend I have this error message:

`1 exception(s):
Exception #0 (Exception): Notice: Undefined index: - in /var/www/mywebsite/vendor/mageplaza/magento-2-seo-extension/Plugin/Title.php on line 91

Exception #0 (Exception): Notice: Undefined index: - in /var/www/mywebsite/vendor/mageplaza/magento-2-seo-extension/Plugin/Title.php on line 91
#0 /var/www/mywebsite/vendor/mageplaza/magento-2-seo-extension/Plugin/Title.php(91): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/var/www/myweb...', 91, Array)
#1 /var/www/mywebsite/vendor/mageplaza/magento-2-seo-extension/Plugin/Title.php(56): Mageplaza\Seo\Plugin\Title->getTitleSeparator()
#2 /var/www/mywebsite/vendor/magento/framework/View/Page/Title.php(99): Mageplaza\Seo\Plugin\Title->addConfigValues('Home page')
#3 /var/www/mywebsite/vendor/magento/framework/View/Page/Title.php(67): Magento\Framework\View\Page\Title->build()
#4 /var/www/mywebsite/vendor/magento/framework/View/Page/Config/Renderer.php(109): Magento\Framework\View\Page\Title->get()
#5 /var/www/mywebsite/vendor/magento/framework/View/Page/Config/Renderer.php(97): Magento\Framework\View\Page\Config\Renderer->renderTitle()
#6 /var/www/mywebsite/vendor/magento/framework/View/Result/Page.php(235): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#7 /var/www/mywebsite/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#8 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#9 /var/www/mywebsite/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#10 /var/www/mywebsite/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#11 /var/www/mywebsite/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#12 /var/www/mywebsite/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#13 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#14 /var/www/mywebsite/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#15 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#16 /var/www/mywebsite/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#17 /var/www/mywebsite/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#18 /var/www/mywebsite/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#19 /var/www/mywebsite/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#20 {main}`

**Comment by afavata** [comment]
Hi @imsamthomas 
Just installed new version 1.2.0 
works like a charm
you can close this issue
Thanks indeed

Alex
